server:
  port: 8080

spring:
  application:
    name: AgenteIAEstoque

  datasource:
    url: jdbc:postgresql://localhost:5001/estoque_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  # 2. Configurações do Hibernate/JPA
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # 3. Configuração do Spring AI (Conexão com o LLM Local)
  ai:
      ollama:
        base-url: http://localhost:11001
        chat:
          options:
            model: llama3.2
            temperature: 0.0
        
        embedding:
          options:
            model: nomic-embed-text

      vectorstore:
        pgvector:
          index-type: HNSW 
          distance-type: COSINE_DISTANCE 
          dimensions: 768 
          initialize-schema: true
      mcp:
            
            # 1. O LADO SERVIDOR (Os Braços / Especialista em Dados)
            server:
              webmvc:
                enabled: true
                # O servidor expõe as ferramentas usando SSE (Server-Sent Events) nestas rotas HTTP
                sse-path: /mcp/sse
                message-path: /mcp/message

            # 2. O LADO CLIENTE (O Cérebro / Llama 3)
            client:
              enabled: true
              name: "AgenteEstoqueClient"
              connections:
                # Podemos ter várias conexões. Aqui criamos uma chamada "servidor-estoque"
                servidor-estoque:
                  type: sse
                  url: http://localhost:8080/mcp/sse

  flyway:
    enabled: true
    baseline-on-migrate: true